version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.1.20
    steps:
      - checkout
      - store_test_results:
          path: .
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Setup environment
          command: |
            cp .env.example .env
            php artisan key:generate
      - run: php artisan test

workflows:
  run_test:
    jobs:
      - test
