version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.1.20
    steps:
      - checkout
      - store_test_results:
          path: .
      - run: php artisan test

workflows:
  run_test:
    jobs:
      - test
